// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: github.com/metaprov/modelaapi/services/dataapp/v1/dataapp.proto

package v1

import (
	context "context"
	v1alpha1 "github.com/metaprov/modelaapi/pkg/apis/inference/v1alpha1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDataAppsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels    map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ListDataAppsRequest) Reset() {
	*x = ListDataAppsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDataAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataAppsRequest) ProtoMessage() {}

func (x *ListDataAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataAppsRequest.ProtoReflect.Descriptor instead.
func (*ListDataAppsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{0}
}

func (x *ListDataAppsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListDataAppsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDataAppsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListDataAppsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items *v1alpha1.DataAppList `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
}

func (x *ListDataAppsResponse) Reset() {
	*x = ListDataAppsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDataAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataAppsResponse) ProtoMessage() {}

func (x *ListDataAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataAppsResponse.ProtoReflect.Descriptor instead.
func (*ListDataAppsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{1}
}

func (x *ListDataAppsResponse) GetItems() *v1alpha1.DataAppList {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateDataAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDataAppResponse) Reset() {
	*x = CreateDataAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDataAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataAppResponse) ProtoMessage() {}

func (x *CreateDataAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataAppResponse.ProtoReflect.Descriptor instead.
func (*CreateDataAppResponse) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{2}
}

type CreateDataAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *v1alpha1.DataApp `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CreateDataAppRequest) Reset() {
	*x = CreateDataAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDataAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataAppRequest) ProtoMessage() {}

func (x *CreateDataAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataAppRequest.ProtoReflect.Descriptor instead.
func (*CreateDataAppRequest) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDataAppRequest) GetItem() *v1alpha1.DataApp {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateDataAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *v1alpha1.DataApp `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *UpdateDataAppRequest) Reset() {
	*x = UpdateDataAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataAppRequest) ProtoMessage() {}

func (x *UpdateDataAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataAppRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataAppRequest) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDataAppRequest) GetItem() *v1alpha1.DataApp {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateDataAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDataAppResponse) Reset() {
	*x = UpdateDataAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataAppResponse) ProtoMessage() {}

func (x *UpdateDataAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataAppResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataAppResponse) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{5}
}

type GetDataAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetDataAppRequest) Reset() {
	*x = GetDataAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataAppRequest) ProtoMessage() {}

func (x *GetDataAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataAppRequest.ProtoReflect.Descriptor instead.
func (*GetDataAppRequest) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{6}
}

func (x *GetDataAppRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetDataAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDataAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *v1alpha1.DataApp `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Yaml string            `protobuf:"bytes,2,opt,name=yaml,proto3" json:"yaml,omitempty"`
}

func (x *GetDataAppResponse) Reset() {
	*x = GetDataAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataAppResponse) ProtoMessage() {}

func (x *GetDataAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataAppResponse.ProtoReflect.Descriptor instead.
func (*GetDataAppResponse) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{7}
}

func (x *GetDataAppResponse) GetItem() *v1alpha1.DataApp {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetDataAppResponse) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type DeleteDataAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteDataAppRequest) Reset() {
	*x = DeleteDataAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataAppRequest) ProtoMessage() {}

func (x *DeleteDataAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataAppRequest) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDataAppRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteDataAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteDataAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDataAppResponse) Reset() {
	*x = DeleteDataAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataAppResponse) ProtoMessage() {}

func (x *DeleteDataAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataAppResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataAppResponse) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{9}
}

type PauseDataAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PauseDataAppRequest) Reset() {
	*x = PauseDataAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseDataAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseDataAppRequest) ProtoMessage() {}

func (x *PauseDataAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseDataAppRequest.ProtoReflect.Descriptor instead.
func (*PauseDataAppRequest) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{10}
}

func (x *PauseDataAppRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PauseDataAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PauseDataAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PauseDataAppResponse) Reset() {
	*x = PauseDataAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseDataAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseDataAppResponse) ProtoMessage() {}

func (x *PauseDataAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseDataAppResponse.ProtoReflect.Descriptor instead.
func (*PauseDataAppResponse) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{11}
}

type ResumeDataAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ResumeDataAppRequest) Reset() {
	*x = ResumeDataAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeDataAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDataAppRequest) ProtoMessage() {}

func (x *ResumeDataAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDataAppRequest.ProtoReflect.Descriptor instead.
func (*ResumeDataAppRequest) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{12}
}

func (x *ResumeDataAppRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResumeDataAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResumeDataAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResumeDataAppResponse) Reset() {
	*x = ResumeDataAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeDataAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDataAppResponse) ProtoMessage() {}

func (x *ResumeDataAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDataAppResponse.ProtoReflect.Descriptor instead.
func (*ResumeDataAppResponse) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{13}
}

type RunDataAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *v1alpha1.DataApp `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *RunDataAppRequest) Reset() {
	*x = RunDataAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunDataAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDataAppRequest) ProtoMessage() {}

func (x *RunDataAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDataAppRequest.ProtoReflect.Descriptor instead.
func (*RunDataAppRequest) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{14}
}

func (x *RunDataAppRequest) GetItem() *v1alpha1.DataApp {
	if x != nil {
		return x.Item
	}
	return nil
}

type RunDataAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunDataAppResponse) Reset() {
	*x = RunDataAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunDataAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDataAppResponse) ProtoMessage() {}

func (x *RunDataAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDataAppResponse.ProtoReflect.Descriptor instead.
func (*RunDataAppResponse) Descriptor() ([]byte, []int) {
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP(), []int{15}
}

var File_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto protoreflect.FileDescriptor

var file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x74,
	0x61, 0x70, 0x72, 0x6f, 0x76, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70,
	0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70,
	0x70, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee, 0x01,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x6a, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x52, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x74,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x69,
	0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6e, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x6e, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x17, 0x0a,
	0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x80, 0x01,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x42, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x79, 0x61, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x61, 0x6d, 0x6c,
	0x22, 0x48, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x50, 0x61, 0x75, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x16, 0x0a, 0x14,
	0x50, 0x61, 0x75, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x48, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x17,
	0x0a, 0x15, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6b, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xfd, 0x0a, 0x0a, 0x0e, 0x44,
	0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0xb8, 0x01,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x73, 0x12, 0x46,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x47, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x62,
	0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0xbe, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x12, 0x47, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x48, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x62, 0x65, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0xb9, 0x01, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x12, 0x44, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x45,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f,
	0x76, 0x31, 0x2f, 0x77, 0x65, 0x62, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x7b,
	0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0xd9, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x12, 0x47, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x48, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x2f, 0x1a, 0x2a, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x62, 0x65, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x2f, 0x7b, 0x77, 0x65, 0x62, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x3a, 0x01,
	0x2a, 0x12, 0xc2, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x41, 0x70, 0x70, 0x12, 0x47, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x48, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72,
	0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x2a, 0x16,
	0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x62, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2f,
	0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0xc5, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x75, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x12, 0x46, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x75, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x47, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x75, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e,
	0x22, 0x1c, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x62, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x3a, 0x70, 0x61, 0x75, 0x73, 0x65, 0x12, 0xc9,
	0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70,
	0x12, 0x47, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x48, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x76, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x22, 0x1d, 0x2f, 0x76, 0x31,
	0x2f, 0x77, 0x65, 0x62, 0x65, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x7b, 0x6e, 0x61,
	0x6d, 0x65, 0x7d, 0x3a, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f,
	0x76, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x61, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescOnce sync.Once
	file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescData = file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDesc
)

func file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescGZIP() []byte {
	file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescOnce.Do(func() {
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescData)
	})
	return file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDescData
}

var file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_goTypes = []interface{}{
	(*ListDataAppsRequest)(nil),   // 0: github.com.metaprov.modelaapi.services.dataapp.v1.ListDataAppsRequest
	(*ListDataAppsResponse)(nil),  // 1: github.com.metaprov.modelaapi.services.dataapp.v1.ListDataAppsResponse
	(*CreateDataAppResponse)(nil), // 2: github.com.metaprov.modelaapi.services.dataapp.v1.CreateDataAppResponse
	(*CreateDataAppRequest)(nil),  // 3: github.com.metaprov.modelaapi.services.dataapp.v1.CreateDataAppRequest
	(*UpdateDataAppRequest)(nil),  // 4: github.com.metaprov.modelaapi.services.dataapp.v1.UpdateDataAppRequest
	(*UpdateDataAppResponse)(nil), // 5: github.com.metaprov.modelaapi.services.dataapp.v1.UpdateDataAppResponse
	(*GetDataAppRequest)(nil),     // 6: github.com.metaprov.modelaapi.services.dataapp.v1.GetDataAppRequest
	(*GetDataAppResponse)(nil),    // 7: github.com.metaprov.modelaapi.services.dataapp.v1.GetDataAppResponse
	(*DeleteDataAppRequest)(nil),  // 8: github.com.metaprov.modelaapi.services.dataapp.v1.DeleteDataAppRequest
	(*DeleteDataAppResponse)(nil), // 9: github.com.metaprov.modelaapi.services.dataapp.v1.DeleteDataAppResponse
	(*PauseDataAppRequest)(nil),   // 10: github.com.metaprov.modelaapi.services.dataapp.v1.PauseDataAppRequest
	(*PauseDataAppResponse)(nil),  // 11: github.com.metaprov.modelaapi.services.dataapp.v1.PauseDataAppResponse
	(*ResumeDataAppRequest)(nil),  // 12: github.com.metaprov.modelaapi.services.dataapp.v1.ResumeDataAppRequest
	(*ResumeDataAppResponse)(nil), // 13: github.com.metaprov.modelaapi.services.dataapp.v1.ResumeDataAppResponse
	(*RunDataAppRequest)(nil),     // 14: github.com.metaprov.modelaapi.services.dataapp.v1.RunDataAppRequest
	(*RunDataAppResponse)(nil),    // 15: github.com.metaprov.modelaapi.services.dataapp.v1.RunDataAppResponse
	nil,                           // 16: github.com.metaprov.modelaapi.services.dataapp.v1.ListDataAppsRequest.LabelsEntry
	(*v1alpha1.DataAppList)(nil),  // 17: github.com.metaprov.modelaapi.pkg.apis.inference.v1alpha1.DataAppList
	(*v1alpha1.DataApp)(nil),      // 18: github.com.metaprov.modelaapi.pkg.apis.inference.v1alpha1.DataApp
}
var file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_depIdxs = []int32{
	16, // 0: github.com.metaprov.modelaapi.services.dataapp.v1.ListDataAppsRequest.labels:type_name -> github.com.metaprov.modelaapi.services.dataapp.v1.ListDataAppsRequest.LabelsEntry
	17, // 1: github.com.metaprov.modelaapi.services.dataapp.v1.ListDataAppsResponse.items:type_name -> github.com.metaprov.modelaapi.pkg.apis.inference.v1alpha1.DataAppList
	18, // 2: github.com.metaprov.modelaapi.services.dataapp.v1.CreateDataAppRequest.item:type_name -> github.com.metaprov.modelaapi.pkg.apis.inference.v1alpha1.DataApp
	18, // 3: github.com.metaprov.modelaapi.services.dataapp.v1.UpdateDataAppRequest.item:type_name -> github.com.metaprov.modelaapi.pkg.apis.inference.v1alpha1.DataApp
	18, // 4: github.com.metaprov.modelaapi.services.dataapp.v1.GetDataAppResponse.item:type_name -> github.com.metaprov.modelaapi.pkg.apis.inference.v1alpha1.DataApp
	18, // 5: github.com.metaprov.modelaapi.services.dataapp.v1.RunDataAppRequest.item:type_name -> github.com.metaprov.modelaapi.pkg.apis.inference.v1alpha1.DataApp
	0,  // 6: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.ListDataApps:input_type -> github.com.metaprov.modelaapi.services.dataapp.v1.ListDataAppsRequest
	3,  // 7: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.CreateDataApp:input_type -> github.com.metaprov.modelaapi.services.dataapp.v1.CreateDataAppRequest
	6,  // 8: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.GetDataApp:input_type -> github.com.metaprov.modelaapi.services.dataapp.v1.GetDataAppRequest
	4,  // 9: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.UpdateDataApp:input_type -> github.com.metaprov.modelaapi.services.dataapp.v1.UpdateDataAppRequest
	8,  // 10: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.DeleteDataApp:input_type -> github.com.metaprov.modelaapi.services.dataapp.v1.DeleteDataAppRequest
	10, // 11: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.PauseDataApp:input_type -> github.com.metaprov.modelaapi.services.dataapp.v1.PauseDataAppRequest
	12, // 12: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.ResumeDataApp:input_type -> github.com.metaprov.modelaapi.services.dataapp.v1.ResumeDataAppRequest
	1,  // 13: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.ListDataApps:output_type -> github.com.metaprov.modelaapi.services.dataapp.v1.ListDataAppsResponse
	2,  // 14: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.CreateDataApp:output_type -> github.com.metaprov.modelaapi.services.dataapp.v1.CreateDataAppResponse
	7,  // 15: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.GetDataApp:output_type -> github.com.metaprov.modelaapi.services.dataapp.v1.GetDataAppResponse
	5,  // 16: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.UpdateDataApp:output_type -> github.com.metaprov.modelaapi.services.dataapp.v1.UpdateDataAppResponse
	9,  // 17: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.DeleteDataApp:output_type -> github.com.metaprov.modelaapi.services.dataapp.v1.DeleteDataAppResponse
	11, // 18: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.PauseDataApp:output_type -> github.com.metaprov.modelaapi.services.dataapp.v1.PauseDataAppResponse
	13, // 19: github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService.ResumeDataApp:output_type -> github.com.metaprov.modelaapi.services.dataapp.v1.ResumeDataAppResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_init() }
func file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_init() {
	if File_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDataAppsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDataAppsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDataAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDataAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauseDataAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauseDataAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeDataAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeDataAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunDataAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunDataAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_goTypes,
		DependencyIndexes: file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_depIdxs,
		MessageInfos:      file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_msgTypes,
	}.Build()
	File_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto = out.File
	file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_rawDesc = nil
	file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_goTypes = nil
	file_github_com_metaprov_modelaapi_services_dataapp_v1_dataapp_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataAppServiceClient is the client API for DataAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataAppServiceClient interface {
	ListDataApps(ctx context.Context, in *ListDataAppsRequest, opts ...grpc.CallOption) (*ListDataAppsResponse, error)
	CreateDataApp(ctx context.Context, in *CreateDataAppRequest, opts ...grpc.CallOption) (*CreateDataAppResponse, error)
	GetDataApp(ctx context.Context, in *GetDataAppRequest, opts ...grpc.CallOption) (*GetDataAppResponse, error)
	UpdateDataApp(ctx context.Context, in *UpdateDataAppRequest, opts ...grpc.CallOption) (*UpdateDataAppResponse, error)
	DeleteDataApp(ctx context.Context, in *DeleteDataAppRequest, opts ...grpc.CallOption) (*DeleteDataAppResponse, error)
	PauseDataApp(ctx context.Context, in *PauseDataAppRequest, opts ...grpc.CallOption) (*PauseDataAppResponse, error)
	ResumeDataApp(ctx context.Context, in *ResumeDataAppRequest, opts ...grpc.CallOption) (*ResumeDataAppResponse, error)
}

type dataAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataAppServiceClient(cc grpc.ClientConnInterface) DataAppServiceClient {
	return &dataAppServiceClient{cc}
}

func (c *dataAppServiceClient) ListDataApps(ctx context.Context, in *ListDataAppsRequest, opts ...grpc.CallOption) (*ListDataAppsResponse, error) {
	out := new(ListDataAppsResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/ListDataApps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAppServiceClient) CreateDataApp(ctx context.Context, in *CreateDataAppRequest, opts ...grpc.CallOption) (*CreateDataAppResponse, error) {
	out := new(CreateDataAppResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/CreateDataApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAppServiceClient) GetDataApp(ctx context.Context, in *GetDataAppRequest, opts ...grpc.CallOption) (*GetDataAppResponse, error) {
	out := new(GetDataAppResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/GetDataApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAppServiceClient) UpdateDataApp(ctx context.Context, in *UpdateDataAppRequest, opts ...grpc.CallOption) (*UpdateDataAppResponse, error) {
	out := new(UpdateDataAppResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/UpdateDataApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAppServiceClient) DeleteDataApp(ctx context.Context, in *DeleteDataAppRequest, opts ...grpc.CallOption) (*DeleteDataAppResponse, error) {
	out := new(DeleteDataAppResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/DeleteDataApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAppServiceClient) PauseDataApp(ctx context.Context, in *PauseDataAppRequest, opts ...grpc.CallOption) (*PauseDataAppResponse, error) {
	out := new(PauseDataAppResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/PauseDataApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAppServiceClient) ResumeDataApp(ctx context.Context, in *ResumeDataAppRequest, opts ...grpc.CallOption) (*ResumeDataAppResponse, error) {
	out := new(ResumeDataAppResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/ResumeDataApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataAppServiceServer is the server API for DataAppService service.
type DataAppServiceServer interface {
	ListDataApps(context.Context, *ListDataAppsRequest) (*ListDataAppsResponse, error)
	CreateDataApp(context.Context, *CreateDataAppRequest) (*CreateDataAppResponse, error)
	GetDataApp(context.Context, *GetDataAppRequest) (*GetDataAppResponse, error)
	UpdateDataApp(context.Context, *UpdateDataAppRequest) (*UpdateDataAppResponse, error)
	DeleteDataApp(context.Context, *DeleteDataAppRequest) (*DeleteDataAppResponse, error)
	PauseDataApp(context.Context, *PauseDataAppRequest) (*PauseDataAppResponse, error)
	ResumeDataApp(context.Context, *ResumeDataAppRequest) (*ResumeDataAppResponse, error)
}

// UnimplementedDataAppServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataAppServiceServer struct {
}

func (*UnimplementedDataAppServiceServer) ListDataApps(context.Context, *ListDataAppsRequest) (*ListDataAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDataApps not implemented")
}
func (*UnimplementedDataAppServiceServer) CreateDataApp(context.Context, *CreateDataAppRequest) (*CreateDataAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataApp not implemented")
}
func (*UnimplementedDataAppServiceServer) GetDataApp(context.Context, *GetDataAppRequest) (*GetDataAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataApp not implemented")
}
func (*UnimplementedDataAppServiceServer) UpdateDataApp(context.Context, *UpdateDataAppRequest) (*UpdateDataAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDataApp not implemented")
}
func (*UnimplementedDataAppServiceServer) DeleteDataApp(context.Context, *DeleteDataAppRequest) (*DeleteDataAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDataApp not implemented")
}
func (*UnimplementedDataAppServiceServer) PauseDataApp(context.Context, *PauseDataAppRequest) (*PauseDataAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseDataApp not implemented")
}
func (*UnimplementedDataAppServiceServer) ResumeDataApp(context.Context, *ResumeDataAppRequest) (*ResumeDataAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeDataApp not implemented")
}

func RegisterDataAppServiceServer(s *grpc.Server, srv DataAppServiceServer) {
	s.RegisterService(&_DataAppService_serviceDesc, srv)
}

func _DataAppService_ListDataApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAppServiceServer).ListDataApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/ListDataApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAppServiceServer).ListDataApps(ctx, req.(*ListDataAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAppService_CreateDataApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAppServiceServer).CreateDataApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/CreateDataApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAppServiceServer).CreateDataApp(ctx, req.(*CreateDataAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAppService_GetDataApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAppServiceServer).GetDataApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/GetDataApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAppServiceServer).GetDataApp(ctx, req.(*GetDataAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAppService_UpdateDataApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAppServiceServer).UpdateDataApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/UpdateDataApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAppServiceServer).UpdateDataApp(ctx, req.(*UpdateDataAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAppService_DeleteDataApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAppServiceServer).DeleteDataApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/DeleteDataApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAppServiceServer).DeleteDataApp(ctx, req.(*DeleteDataAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAppService_PauseDataApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseDataAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAppServiceServer).PauseDataApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/PauseDataApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAppServiceServer).PauseDataApp(ctx, req.(*PauseDataAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAppService_ResumeDataApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeDataAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAppServiceServer).ResumeDataApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService/ResumeDataApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAppServiceServer).ResumeDataApp(ctx, req.(*ResumeDataAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataAppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.metaprov.modelaapi.services.dataapp.v1.DataAppService",
	HandlerType: (*DataAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDataApps",
			Handler:    _DataAppService_ListDataApps_Handler,
		},
		{
			MethodName: "CreateDataApp",
			Handler:    _DataAppService_CreateDataApp_Handler,
		},
		{
			MethodName: "GetDataApp",
			Handler:    _DataAppService_GetDataApp_Handler,
		},
		{
			MethodName: "UpdateDataApp",
			Handler:    _DataAppService_UpdateDataApp_Handler,
		},
		{
			MethodName: "DeleteDataApp",
			Handler:    _DataAppService_DeleteDataApp_Handler,
		},
		{
			MethodName: "PauseDataApp",
			Handler:    _DataAppService_PauseDataApp_Handler,
		},
		{
			MethodName: "ResumeDataApp",
			Handler:    _DataAppService_ResumeDataApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/metaprov/modelaapi/services/dataapp/v1/dataapp.proto",
}
