codecov:
  require_ci_to_pass: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: auto
      modelaapi-unit-tests:
        target: auto
        flags:
          - unit-tests
      modelaapi-integration-tests:
        target: auto
        flags:
          - integration-tests
      modelaapi-e2e-tests:
        target: auto
        flags:
          - e2e-tests

ignore:
  - "**/testing/mock_*.go"
  - "**/*generate*.go"
  - "pkg/client"
  - "**/*.pb.go"
  - "third_party"