apiVersion: inference.modela.ai/v1alpha1
kind: Prediction
metadata:
  name: ouod-batch-prediction
  namespace: default-product
spec:
  run:
    maxPreviousRuns: 5
    schedule:
      enabled: true
      type: hourly
  input:
    location:
      database:
        connectionName: oneuponedown
        sql: SELECT * FROM prediction_view_new;
  labeled: false
  model:
    name: model-20230711-1659570
  output:
    action: upsert
    includeFeatures: false
    location:
      database:
        connectionName: oneuponedown
        table: prediction_alt_new
  resources:
    custom: false
    workloadName: general-large
  servingSiteName: modela-serving-site