apiVersion: inference.modela.ai/v1alpha1
kind: Prediction
metadata:
  name: ouod-batch-prediction
  namespace: default-product
spec:
  abort: false
  activeDeadlineSeconds: 600
  createDataset: false
  forecastSpec:
    horizon:
      start: 0
  schedule:
    enabled: true
    type: hourly
  input:
    format:
      csv:
        commentChars: '#'
        compression: none
        delimiter: comma
        encoding: utf-8
        escapeChar: single-quote
        hasIndexColumn: false
        header: true
        maxRows: 0
        nullValues: ''
        quote: double-quote
        skipRows: 0
        strict: false
      excel:
        data:
          entireSheet: false
        firstSheetWithData: false
      fileType: csv
      parquet:
        engine: auto
    location:
      bucket: ''
      connection: oneuponedown
      database: ''
      path: ''
      sql: SELECT * FROM prediction_view;
      table: prediction_view
      topic: ''
      type: view
      url: ''
  labeled: false
  modelRef:
    name: model-20230711-1659570
    namespace: default-product
  output:
    IncludeShapValues: false
    action: upsert
    createTableIfNotExist: false
    datasetName: ''
    detectOutliers: false
    format: csv
    includeFeatures: false
    location:
      bucket: ''
      connection: oneuponedown
      database: ''
      path: ''
      sql: ''
      table: prediction_alt
      topic: ''
      type: table
      url: ''
  owner: admin
  partitionLocation: {}
  resources:
    custom: false
    workloadName: general-large
  servingSiteRef:
    name: modela-serving-site
    namespace: modela
  unitTests: {}
  versionName: v1