// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: services/catalog/catalog.proto

package catalog

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	v1alpha1 "github.com/metaprov/modeldapi/pkg/apis/catalog/v1alpha1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ListAlgorithmsRequest struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListAlgorithmsRequest) Reset()         { *m = ListAlgorithmsRequest{} }
func (m *ListAlgorithmsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAlgorithmsRequest) ProtoMessage()    {}
func (*ListAlgorithmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{0}
}
func (m *ListAlgorithmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlgorithmsRequest.Unmarshal(m, b)
}
func (m *ListAlgorithmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlgorithmsRequest.Marshal(b, m, deterministic)
}
func (m *ListAlgorithmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlgorithmsRequest.Merge(m, src)
}
func (m *ListAlgorithmsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAlgorithmsRequest.Size(m)
}
func (m *ListAlgorithmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlgorithmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlgorithmsRequest proto.InternalMessageInfo

func (m *ListAlgorithmsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListAlgorithmsRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ListAlgorithmsResponse struct {
	Items                *v1alpha1.AlgorithmList `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListAlgorithmsResponse) Reset()         { *m = ListAlgorithmsResponse{} }
func (m *ListAlgorithmsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAlgorithmsResponse) ProtoMessage()    {}
func (*ListAlgorithmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{1}
}
func (m *ListAlgorithmsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlgorithmsResponse.Unmarshal(m, b)
}
func (m *ListAlgorithmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlgorithmsResponse.Marshal(b, m, deterministic)
}
func (m *ListAlgorithmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlgorithmsResponse.Merge(m, src)
}
func (m *ListAlgorithmsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAlgorithmsResponse.Size(m)
}
func (m *ListAlgorithmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlgorithmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlgorithmsResponse proto.InternalMessageInfo

func (m *ListAlgorithmsResponse) GetItems() *v1alpha1.AlgorithmList {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetAlgorithmRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlgorithmRequest) Reset()         { *m = GetAlgorithmRequest{} }
func (m *GetAlgorithmRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlgorithmRequest) ProtoMessage()    {}
func (*GetAlgorithmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{2}
}
func (m *GetAlgorithmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlgorithmRequest.Unmarshal(m, b)
}
func (m *GetAlgorithmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlgorithmRequest.Marshal(b, m, deterministic)
}
func (m *GetAlgorithmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlgorithmRequest.Merge(m, src)
}
func (m *GetAlgorithmRequest) XXX_Size() int {
	return xxx_messageInfo_GetAlgorithmRequest.Size(m)
}
func (m *GetAlgorithmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlgorithmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlgorithmRequest proto.InternalMessageInfo

func (m *GetAlgorithmRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetAlgorithmRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetAlgorithmResponse struct {
	Item                 *v1alpha1.Algorithm `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAlgorithmResponse) Reset()         { *m = GetAlgorithmResponse{} }
func (m *GetAlgorithmResponse) String() string { return proto.CompactTextString(m) }
func (*GetAlgorithmResponse) ProtoMessage()    {}
func (*GetAlgorithmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{3}
}
func (m *GetAlgorithmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlgorithmResponse.Unmarshal(m, b)
}
func (m *GetAlgorithmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlgorithmResponse.Marshal(b, m, deterministic)
}
func (m *GetAlgorithmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlgorithmResponse.Merge(m, src)
}
func (m *GetAlgorithmResponse) XXX_Size() int {
	return xxx_messageInfo_GetAlgorithmResponse.Size(m)
}
func (m *GetAlgorithmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlgorithmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlgorithmResponse proto.InternalMessageInfo

func (m *GetAlgorithmResponse) GetItem() *v1alpha1.Algorithm {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListMLFrameworksRequest struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListMLFrameworksRequest) Reset()         { *m = ListMLFrameworksRequest{} }
func (m *ListMLFrameworksRequest) String() string { return proto.CompactTextString(m) }
func (*ListMLFrameworksRequest) ProtoMessage()    {}
func (*ListMLFrameworksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{4}
}
func (m *ListMLFrameworksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMLFrameworksRequest.Unmarshal(m, b)
}
func (m *ListMLFrameworksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMLFrameworksRequest.Marshal(b, m, deterministic)
}
func (m *ListMLFrameworksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMLFrameworksRequest.Merge(m, src)
}
func (m *ListMLFrameworksRequest) XXX_Size() int {
	return xxx_messageInfo_ListMLFrameworksRequest.Size(m)
}
func (m *ListMLFrameworksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMLFrameworksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMLFrameworksRequest proto.InternalMessageInfo

func (m *ListMLFrameworksRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListMLFrameworksRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ListMLFrameworksResponse struct {
	Items                *v1alpha1.MLFrameworkList `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListMLFrameworksResponse) Reset()         { *m = ListMLFrameworksResponse{} }
func (m *ListMLFrameworksResponse) String() string { return proto.CompactTextString(m) }
func (*ListMLFrameworksResponse) ProtoMessage()    {}
func (*ListMLFrameworksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{5}
}
func (m *ListMLFrameworksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMLFrameworksResponse.Unmarshal(m, b)
}
func (m *ListMLFrameworksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMLFrameworksResponse.Marshal(b, m, deterministic)
}
func (m *ListMLFrameworksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMLFrameworksResponse.Merge(m, src)
}
func (m *ListMLFrameworksResponse) XXX_Size() int {
	return xxx_messageInfo_ListMLFrameworksResponse.Size(m)
}
func (m *ListMLFrameworksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMLFrameworksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMLFrameworksResponse proto.InternalMessageInfo

func (m *ListMLFrameworksResponse) GetItems() *v1alpha1.MLFrameworkList {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetMLFrameworkRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMLFrameworkRequest) Reset()         { *m = GetMLFrameworkRequest{} }
func (m *GetMLFrameworkRequest) String() string { return proto.CompactTextString(m) }
func (*GetMLFrameworkRequest) ProtoMessage()    {}
func (*GetMLFrameworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{6}
}
func (m *GetMLFrameworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMLFrameworkRequest.Unmarshal(m, b)
}
func (m *GetMLFrameworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMLFrameworkRequest.Marshal(b, m, deterministic)
}
func (m *GetMLFrameworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMLFrameworkRequest.Merge(m, src)
}
func (m *GetMLFrameworkRequest) XXX_Size() int {
	return xxx_messageInfo_GetMLFrameworkRequest.Size(m)
}
func (m *GetMLFrameworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMLFrameworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMLFrameworkRequest proto.InternalMessageInfo

func (m *GetMLFrameworkRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetMLFrameworkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetMLFrameworkResponse struct {
	Item                 *v1alpha1.MLFramework `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetMLFrameworkResponse) Reset()         { *m = GetMLFrameworkResponse{} }
func (m *GetMLFrameworkResponse) String() string { return proto.CompactTextString(m) }
func (*GetMLFrameworkResponse) ProtoMessage()    {}
func (*GetMLFrameworkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{7}
}
func (m *GetMLFrameworkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMLFrameworkResponse.Unmarshal(m, b)
}
func (m *GetMLFrameworkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMLFrameworkResponse.Marshal(b, m, deterministic)
}
func (m *GetMLFrameworkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMLFrameworkResponse.Merge(m, src)
}
func (m *GetMLFrameworkResponse) XXX_Size() int {
	return xxx_messageInfo_GetMLFrameworkResponse.Size(m)
}
func (m *GetMLFrameworkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMLFrameworkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMLFrameworkResponse proto.InternalMessageInfo

func (m *GetMLFrameworkResponse) GetItem() *v1alpha1.MLFramework {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListCloudsRequest struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListCloudsRequest) Reset()         { *m = ListCloudsRequest{} }
func (m *ListCloudsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCloudsRequest) ProtoMessage()    {}
func (*ListCloudsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{8}
}
func (m *ListCloudsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCloudsRequest.Unmarshal(m, b)
}
func (m *ListCloudsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCloudsRequest.Marshal(b, m, deterministic)
}
func (m *ListCloudsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCloudsRequest.Merge(m, src)
}
func (m *ListCloudsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCloudsRequest.Size(m)
}
func (m *ListCloudsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCloudsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCloudsRequest proto.InternalMessageInfo

func (m *ListCloudsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListCloudsRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ListCloudsResponse struct {
	Items                *v1alpha1.CloudList `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListCloudsResponse) Reset()         { *m = ListCloudsResponse{} }
func (m *ListCloudsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCloudsResponse) ProtoMessage()    {}
func (*ListCloudsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{9}
}
func (m *ListCloudsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCloudsResponse.Unmarshal(m, b)
}
func (m *ListCloudsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCloudsResponse.Marshal(b, m, deterministic)
}
func (m *ListCloudsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCloudsResponse.Merge(m, src)
}
func (m *ListCloudsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCloudsResponse.Size(m)
}
func (m *ListCloudsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCloudsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCloudsResponse proto.InternalMessageInfo

func (m *ListCloudsResponse) GetItems() *v1alpha1.CloudList {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetCloudRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCloudRequest) Reset()         { *m = GetCloudRequest{} }
func (m *GetCloudRequest) String() string { return proto.CompactTextString(m) }
func (*GetCloudRequest) ProtoMessage()    {}
func (*GetCloudRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{10}
}
func (m *GetCloudRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCloudRequest.Unmarshal(m, b)
}
func (m *GetCloudRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCloudRequest.Marshal(b, m, deterministic)
}
func (m *GetCloudRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCloudRequest.Merge(m, src)
}
func (m *GetCloudRequest) XXX_Size() int {
	return xxx_messageInfo_GetCloudRequest.Size(m)
}
func (m *GetCloudRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCloudRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCloudRequest proto.InternalMessageInfo

func (m *GetCloudRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetCloudRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCloudResponse struct {
	Item                 *v1alpha1.Cloud `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetCloudResponse) Reset()         { *m = GetCloudResponse{} }
func (m *GetCloudResponse) String() string { return proto.CompactTextString(m) }
func (*GetCloudResponse) ProtoMessage()    {}
func (*GetCloudResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{11}
}
func (m *GetCloudResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCloudResponse.Unmarshal(m, b)
}
func (m *GetCloudResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCloudResponse.Marshal(b, m, deterministic)
}
func (m *GetCloudResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCloudResponse.Merge(m, src)
}
func (m *GetCloudResponse) XXX_Size() int {
	return xxx_messageInfo_GetCloudResponse.Size(m)
}
func (m *GetCloudResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCloudResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCloudResponse proto.InternalMessageInfo

func (m *GetCloudResponse) GetItem() *v1alpha1.Cloud {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListPublicDatasetsRequest struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListPublicDatasetsRequest) Reset()         { *m = ListPublicDatasetsRequest{} }
func (m *ListPublicDatasetsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPublicDatasetsRequest) ProtoMessage()    {}
func (*ListPublicDatasetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{12}
}
func (m *ListPublicDatasetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublicDatasetsRequest.Unmarshal(m, b)
}
func (m *ListPublicDatasetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublicDatasetsRequest.Marshal(b, m, deterministic)
}
func (m *ListPublicDatasetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublicDatasetsRequest.Merge(m, src)
}
func (m *ListPublicDatasetsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPublicDatasetsRequest.Size(m)
}
func (m *ListPublicDatasetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublicDatasetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublicDatasetsRequest proto.InternalMessageInfo

func (m *ListPublicDatasetsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListPublicDatasetsRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ListPublicDatasetsResponse struct {
	Items                *v1alpha1.PublicDatasetList `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListPublicDatasetsResponse) Reset()         { *m = ListPublicDatasetsResponse{} }
func (m *ListPublicDatasetsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPublicDatasetsResponse) ProtoMessage()    {}
func (*ListPublicDatasetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{13}
}
func (m *ListPublicDatasetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublicDatasetsResponse.Unmarshal(m, b)
}
func (m *ListPublicDatasetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublicDatasetsResponse.Marshal(b, m, deterministic)
}
func (m *ListPublicDatasetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublicDatasetsResponse.Merge(m, src)
}
func (m *ListPublicDatasetsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPublicDatasetsResponse.Size(m)
}
func (m *ListPublicDatasetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublicDatasetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublicDatasetsResponse proto.InternalMessageInfo

func (m *ListPublicDatasetsResponse) GetItems() *v1alpha1.PublicDatasetList {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetPublicDatasetRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPublicDatasetRequest) Reset()         { *m = GetPublicDatasetRequest{} }
func (m *GetPublicDatasetRequest) String() string { return proto.CompactTextString(m) }
func (*GetPublicDatasetRequest) ProtoMessage()    {}
func (*GetPublicDatasetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{14}
}
func (m *GetPublicDatasetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicDatasetRequest.Unmarshal(m, b)
}
func (m *GetPublicDatasetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicDatasetRequest.Marshal(b, m, deterministic)
}
func (m *GetPublicDatasetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicDatasetRequest.Merge(m, src)
}
func (m *GetPublicDatasetRequest) XXX_Size() int {
	return xxx_messageInfo_GetPublicDatasetRequest.Size(m)
}
func (m *GetPublicDatasetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicDatasetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicDatasetRequest proto.InternalMessageInfo

func (m *GetPublicDatasetRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetPublicDatasetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPublicDatasetResponse struct {
	Item                 *v1alpha1.PublicDataset `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetPublicDatasetResponse) Reset()         { *m = GetPublicDatasetResponse{} }
func (m *GetPublicDatasetResponse) String() string { return proto.CompactTextString(m) }
func (*GetPublicDatasetResponse) ProtoMessage()    {}
func (*GetPublicDatasetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{15}
}
func (m *GetPublicDatasetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicDatasetResponse.Unmarshal(m, b)
}
func (m *GetPublicDatasetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicDatasetResponse.Marshal(b, m, deterministic)
}
func (m *GetPublicDatasetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicDatasetResponse.Merge(m, src)
}
func (m *GetPublicDatasetResponse) XXX_Size() int {
	return xxx_messageInfo_GetPublicDatasetResponse.Size(m)
}
func (m *GetPublicDatasetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicDatasetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicDatasetResponse proto.InternalMessageInfo

func (m *GetPublicDatasetResponse) GetItem() *v1alpha1.PublicDataset {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListPretrainedModelsRequest struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListPretrainedModelsRequest) Reset()         { *m = ListPretrainedModelsRequest{} }
func (m *ListPretrainedModelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPretrainedModelsRequest) ProtoMessage()    {}
func (*ListPretrainedModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{16}
}
func (m *ListPretrainedModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPretrainedModelsRequest.Unmarshal(m, b)
}
func (m *ListPretrainedModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPretrainedModelsRequest.Marshal(b, m, deterministic)
}
func (m *ListPretrainedModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPretrainedModelsRequest.Merge(m, src)
}
func (m *ListPretrainedModelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPretrainedModelsRequest.Size(m)
}
func (m *ListPretrainedModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPretrainedModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPretrainedModelsRequest proto.InternalMessageInfo

func (m *ListPretrainedModelsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListPretrainedModelsRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ListPretrainedModelsResponse struct {
	Items                *v1alpha1.PretrainedModelList `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListPretrainedModelsResponse) Reset()         { *m = ListPretrainedModelsResponse{} }
func (m *ListPretrainedModelsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPretrainedModelsResponse) ProtoMessage()    {}
func (*ListPretrainedModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{17}
}
func (m *ListPretrainedModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPretrainedModelsResponse.Unmarshal(m, b)
}
func (m *ListPretrainedModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPretrainedModelsResponse.Marshal(b, m, deterministic)
}
func (m *ListPretrainedModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPretrainedModelsResponse.Merge(m, src)
}
func (m *ListPretrainedModelsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPretrainedModelsResponse.Size(m)
}
func (m *ListPretrainedModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPretrainedModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPretrainedModelsResponse proto.InternalMessageInfo

func (m *ListPretrainedModelsResponse) GetItems() *v1alpha1.PretrainedModelList {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetPretrainedModelRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPretrainedModelRequest) Reset()         { *m = GetPretrainedModelRequest{} }
func (m *GetPretrainedModelRequest) String() string { return proto.CompactTextString(m) }
func (*GetPretrainedModelRequest) ProtoMessage()    {}
func (*GetPretrainedModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{18}
}
func (m *GetPretrainedModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPretrainedModelRequest.Unmarshal(m, b)
}
func (m *GetPretrainedModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPretrainedModelRequest.Marshal(b, m, deterministic)
}
func (m *GetPretrainedModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPretrainedModelRequest.Merge(m, src)
}
func (m *GetPretrainedModelRequest) XXX_Size() int {
	return xxx_messageInfo_GetPretrainedModelRequest.Size(m)
}
func (m *GetPretrainedModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPretrainedModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPretrainedModelRequest proto.InternalMessageInfo

func (m *GetPretrainedModelRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetPretrainedModelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPretrainedModelResponse struct {
	Item                 *v1alpha1.PretrainedModel `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetPretrainedModelResponse) Reset()         { *m = GetPretrainedModelResponse{} }
func (m *GetPretrainedModelResponse) String() string { return proto.CompactTextString(m) }
func (*GetPretrainedModelResponse) ProtoMessage()    {}
func (*GetPretrainedModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{19}
}
func (m *GetPretrainedModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPretrainedModelResponse.Unmarshal(m, b)
}
func (m *GetPretrainedModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPretrainedModelResponse.Marshal(b, m, deterministic)
}
func (m *GetPretrainedModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPretrainedModelResponse.Merge(m, src)
}
func (m *GetPretrainedModelResponse) XXX_Size() int {
	return xxx_messageInfo_GetPretrainedModelResponse.Size(m)
}
func (m *GetPretrainedModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPretrainedModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPretrainedModelResponse proto.InternalMessageInfo

func (m *GetPretrainedModelResponse) GetItem() *v1alpha1.PretrainedModel {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListWorkloadClassesRequest struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListWorkloadClassesRequest) Reset()         { *m = ListWorkloadClassesRequest{} }
func (m *ListWorkloadClassesRequest) String() string { return proto.CompactTextString(m) }
func (*ListWorkloadClassesRequest) ProtoMessage()    {}
func (*ListWorkloadClassesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{20}
}
func (m *ListWorkloadClassesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkloadClassesRequest.Unmarshal(m, b)
}
func (m *ListWorkloadClassesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkloadClassesRequest.Marshal(b, m, deterministic)
}
func (m *ListWorkloadClassesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkloadClassesRequest.Merge(m, src)
}
func (m *ListWorkloadClassesRequest) XXX_Size() int {
	return xxx_messageInfo_ListWorkloadClassesRequest.Size(m)
}
func (m *ListWorkloadClassesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkloadClassesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkloadClassesRequest proto.InternalMessageInfo

func (m *ListWorkloadClassesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListWorkloadClassesRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ListWorkloadClassesResponse struct {
	Items                *v1alpha1.WorkloadClassList `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListWorkloadClassesResponse) Reset()         { *m = ListWorkloadClassesResponse{} }
func (m *ListWorkloadClassesResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkloadClassesResponse) ProtoMessage()    {}
func (*ListWorkloadClassesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{21}
}
func (m *ListWorkloadClassesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkloadClassesResponse.Unmarshal(m, b)
}
func (m *ListWorkloadClassesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkloadClassesResponse.Marshal(b, m, deterministic)
}
func (m *ListWorkloadClassesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkloadClassesResponse.Merge(m, src)
}
func (m *ListWorkloadClassesResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkloadClassesResponse.Size(m)
}
func (m *ListWorkloadClassesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkloadClassesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkloadClassesResponse proto.InternalMessageInfo

func (m *ListWorkloadClassesResponse) GetItems() *v1alpha1.WorkloadClassList {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetWorkloadClassRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkloadClassRequest) Reset()         { *m = GetWorkloadClassRequest{} }
func (m *GetWorkloadClassRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkloadClassRequest) ProtoMessage()    {}
func (*GetWorkloadClassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{22}
}
func (m *GetWorkloadClassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkloadClassRequest.Unmarshal(m, b)
}
func (m *GetWorkloadClassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkloadClassRequest.Marshal(b, m, deterministic)
}
func (m *GetWorkloadClassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkloadClassRequest.Merge(m, src)
}
func (m *GetWorkloadClassRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkloadClassRequest.Size(m)
}
func (m *GetWorkloadClassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkloadClassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkloadClassRequest proto.InternalMessageInfo

func (m *GetWorkloadClassRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetWorkloadClassRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type GetWorkloadClassResponse struct {
	Item                 *v1alpha1.WorkloadClass `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetWorkloadClassResponse) Reset()         { *m = GetWorkloadClassResponse{} }
func (m *GetWorkloadClassResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkloadClassResponse) ProtoMessage()    {}
func (*GetWorkloadClassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3746b6f7f299994, []int{23}
}
func (m *GetWorkloadClassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkloadClassResponse.Unmarshal(m, b)
}
func (m *GetWorkloadClassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkloadClassResponse.Marshal(b, m, deterministic)
}
func (m *GetWorkloadClassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkloadClassResponse.Merge(m, src)
}
func (m *GetWorkloadClassResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkloadClassResponse.Size(m)
}
func (m *GetWorkloadClassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkloadClassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkloadClassResponse proto.InternalMessageInfo

func (m *GetWorkloadClassResponse) GetItem() *v1alpha1.WorkloadClass {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*ListAlgorithmsRequest)(nil), "github.com.metaprov.modeld.services.catalog.ListAlgorithmsRequest")
	proto.RegisterMapType((map[string]string)(nil), "github.com.metaprov.modeld.services.catalog.ListAlgorithmsRequest.LabelsEntry")
	proto.RegisterType((*ListAlgorithmsResponse)(nil), "github.com.metaprov.modeld.services.catalog.ListAlgorithmsResponse")
	proto.RegisterType((*GetAlgorithmRequest)(nil), "github.com.metaprov.modeld.services.catalog.GetAlgorithmRequest")
	proto.RegisterType((*GetAlgorithmResponse)(nil), "github.com.metaprov.modeld.services.catalog.GetAlgorithmResponse")
	proto.RegisterType((*ListMLFrameworksRequest)(nil), "github.com.metaprov.modeld.services.catalog.ListMLFrameworksRequest")
	proto.RegisterMapType((map[string]string)(nil), "github.com.metaprov.modeld.services.catalog.ListMLFrameworksRequest.LabelsEntry")
	proto.RegisterType((*ListMLFrameworksResponse)(nil), "github.com.metaprov.modeld.services.catalog.ListMLFrameworksResponse")
	proto.RegisterType((*GetMLFrameworkRequest)(nil), "github.com.metaprov.modeld.services.catalog.GetMLFrameworkRequest")
	proto.RegisterType((*GetMLFrameworkResponse)(nil), "github.com.metaprov.modeld.services.catalog.GetMLFrameworkResponse")
	proto.RegisterType((*ListCloudsRequest)(nil), "github.com.metaprov.modeld.services.catalog.ListCloudsRequest")
	proto.RegisterMapType((map[string]string)(nil), "github.com.metaprov.modeld.services.catalog.ListCloudsRequest.LabelsEntry")
	proto.RegisterType((*ListCloudsResponse)(nil), "github.com.metaprov.modeld.services.catalog.ListCloudsResponse")
	proto.RegisterType((*GetCloudRequest)(nil), "github.com.metaprov.modeld.services.catalog.GetCloudRequest")
	proto.RegisterType((*GetCloudResponse)(nil), "github.com.metaprov.modeld.services.catalog.GetCloudResponse")
	proto.RegisterType((*ListPublicDatasetsRequest)(nil), "github.com.metaprov.modeld.services.catalog.ListPublicDatasetsRequest")
	proto.RegisterMapType((map[string]string)(nil), "github.com.metaprov.modeld.services.catalog.ListPublicDatasetsRequest.LabelsEntry")
	proto.RegisterType((*ListPublicDatasetsResponse)(nil), "github.com.metaprov.modeld.services.catalog.ListPublicDatasetsResponse")
	proto.RegisterType((*GetPublicDatasetRequest)(nil), "github.com.metaprov.modeld.services.catalog.GetPublicDatasetRequest")
	proto.RegisterType((*GetPublicDatasetResponse)(nil), "github.com.metaprov.modeld.services.catalog.GetPublicDatasetResponse")
	proto.RegisterType((*ListPretrainedModelsRequest)(nil), "github.com.metaprov.modeld.services.catalog.ListPretrainedModelsRequest")
	proto.RegisterMapType((map[string]string)(nil), "github.com.metaprov.modeld.services.catalog.ListPretrainedModelsRequest.LabelsEntry")
	proto.RegisterType((*ListPretrainedModelsResponse)(nil), "github.com.metaprov.modeld.services.catalog.ListPretrainedModelsResponse")
	proto.RegisterType((*GetPretrainedModelRequest)(nil), "github.com.metaprov.modeld.services.catalog.GetPretrainedModelRequest")
	proto.RegisterType((*GetPretrainedModelResponse)(nil), "github.com.metaprov.modeld.services.catalog.GetPretrainedModelResponse")
	proto.RegisterType((*ListWorkloadClassesRequest)(nil), "github.com.metaprov.modeld.services.catalog.ListWorkloadClassesRequest")
	proto.RegisterMapType((map[string]string)(nil), "github.com.metaprov.modeld.services.catalog.ListWorkloadClassesRequest.LabelsEntry")
	proto.RegisterType((*ListWorkloadClassesResponse)(nil), "github.com.metaprov.modeld.services.catalog.ListWorkloadClassesResponse")
	proto.RegisterType((*GetWorkloadClassRequest)(nil), "github.com.metaprov.modeld.services.catalog.GetWorkloadClassRequest")
	proto.RegisterType((*GetWorkloadClassResponse)(nil), "github.com.metaprov.modeld.services.catalog.GetWorkloadClassResponse")
}

func init() { proto.RegisterFile("services/catalog/catalog.proto", fileDescriptor_b3746b6f7f299994) }

var fileDescriptor_b3746b6f7f299994 = []byte{
	// 989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4d, 0x8f, 0xdb, 0x44,
	0x18, 0xd6, 0xa4, 0x1f, 0xa2, 0xef, 0xf6, 0x63, 0x3b, 0xbb, 0xdb, 0x24, 0xee, 0x02, 0xc5, 0xa7,
	0x4a, 0x48, 0x36, 0xbb, 0x5c, 0x00, 0x41, 0xa1, 0x9b, 0xed, 0x66, 0x29, 0x59, 0x54, 0xa5, 0x08,
	0x50, 0x85, 0x10, 0x93, 0x64, 0xd6, 0x31, 0xb1, 0x3d, 0xc6, 0x76, 0x82, 0x5a, 0x04, 0x48, 0xfd,
	0x0b, 0xfc, 0x02, 0xf8, 0x03, 0x48, 0xdc, 0xe0, 0x88, 0xe0, 0x8e, 0xc4, 0x85, 0x03, 0x07, 0x84,
	0xfa, 0x43, 0xaa, 0x19, 0x8f, 0x63, 0x8f, 0xe3, 0x56, 0xf1, 0xc7, 0x29, 0x89, 0x93, 0x79, 0x9e,
	0xe7, 0x7d, 0xde, 0x67, 0xc6, 0x6f, 0x0c, 0x2f, 0x85, 0x34, 0x58, 0xd8, 0x63, 0x1a, 0x9a, 0x63,
	0x12, 0x11, 0x87, 0x59, 0xc9, 0xab, 0xe1, 0x07, 0x2c, 0x62, 0xf8, 0x55, 0xcb, 0x8e, 0xa6, 0xf3,
	0x91, 0x31, 0x66, 0xae, 0xe1, 0xd2, 0x88, 0xf8, 0x01, 0x5b, 0x18, 0x2e, 0x9b, 0x50, 0x67, 0x62,
	0x24, 0x4b, 0x0d, 0xb9, 0x44, 0xdb, 0xb5, 0x18, 0xb3, 0x1c, 0x6a, 0x12, 0xdf, 0x36, 0x89, 0xe7,
	0xb1, 0x88, 0x44, 0x36, 0xf3, 0xc2, 0x18, 0x4a, 0xeb, 0xa7, 0x50, 0x66, 0x02, 0x65, 0xc6, 0x50,
	0x7c, 0x81, 0x3f, 0xb3, 0xf8, 0xc2, 0x54, 0xc8, 0x62, 0x8f, 0x38, 0xfe, 0x94, 0xec, 0x99, 0x16,
	0xf5, 0x68, 0x40, 0x22, 0x3a, 0x89, 0x81, 0xf4, 0x7f, 0x10, 0xec, 0x0c, 0xec, 0x30, 0xba, 0xed,
	0x58, 0x2c, 0xb0, 0xa3, 0xa9, 0x1b, 0x0e, 0xe9, 0x57, 0x73, 0x1a, 0x46, 0x78, 0x17, 0x2e, 0x78,
	0xc4, 0xa5, 0xa1, 0x4f, 0xc6, 0xb4, 0x83, 0x6e, 0xa0, 0x9b, 0x17, 0x86, 0xe9, 0x05, 0x7c, 0x0a,
	0xe7, 0x1d, 0x32, 0xa2, 0x4e, 0xd8, 0x69, 0xdd, 0x38, 0x73, 0x73, 0x63, 0xff, 0x43, 0xa3, 0x44,
	0x71, 0x46, 0x21, 0xa3, 0x31, 0x10, 0x80, 0x77, 0xbc, 0x28, 0x78, 0x38, 0x94, 0xe8, 0xda, 0x9b,
	0xb0, 0x91, 0xb9, 0x8c, 0x37, 0xe1, 0xcc, 0x8c, 0x3e, 0x94, 0x72, 0xf8, 0x5b, 0xbc, 0x0d, 0xe7,
	0x16, 0xc4, 0x99, 0xd3, 0x4e, 0x4b, 0x5c, 0x8b, 0x3f, 0xbc, 0xd5, 0x7a, 0x03, 0xe9, 0x0b, 0xb8,
	0x96, 0xe7, 0x09, 0x7d, 0xe6, 0x85, 0x14, 0x7f, 0x06, 0xe7, 0xec, 0x88, 0xba, 0xa1, 0xc0, 0xd9,
	0xd8, 0x3f, 0x7a, 0x8e, 0x76, 0xe2, 0xdb, 0x86, 0x3f, 0xb3, 0x0c, 0xee, 0xe6, 0x52, 0x7e, 0xe2,
	0xa6, 0xb1, 0xc4, 0xe6, 0x44, 0xc3, 0x18, 0x54, 0xef, 0xc3, 0x56, 0x9f, 0xa6, 0xb4, 0xeb, 0xf9,
	0x89, 0xe1, 0x2c, 0xff, 0x20, 0xab, 0x10, 0xef, 0x75, 0x0f, 0xb6, 0x55, 0x20, 0x29, 0xff, 0x63,
	0x38, 0xcb, 0x99, 0xa4, 0xfa, 0x83, 0xfa, 0xea, 0x87, 0x02, 0x4f, 0xff, 0x17, 0x41, 0x9b, 0x17,
	0x72, 0x32, 0x38, 0x0a, 0x88, 0x4b, 0xbf, 0x66, 0xc1, 0x6c, 0xcd, 0x34, 0x4c, 0x73, 0x69, 0xb8,
	0x57, 0x3a, 0x0d, 0x05, 0x9c, 0x4d, 0xe7, 0xe1, 0x11, 0x74, 0x56, 0x99, 0xa4, 0xa5, 0x9f, 0xab,
	0x89, 0x38, 0xae, 0xec, 0x69, 0x06, 0x3d, 0x9b, 0x89, 0xf7, 0x61, 0xa7, 0x4f, 0xb3, 0xd4, 0xd5,
	0x53, 0x11, 0xc0, 0xb5, 0x3c, 0x94, 0x2c, 0xe2, 0x53, 0x25, 0x17, 0x87, 0x4d, 0xd4, 0x20, 0x93,
	0xf1, 0x17, 0x82, 0xab, 0xbc, 0x9c, 0x9e, 0xc3, 0xe6, 0x93, 0x35, 0x33, 0x31, 0xca, 0x65, 0xe2,
	0x6e, 0xe9, 0x4c, 0x28, 0x6c, 0x4d, 0xa7, 0xc1, 0x03, 0x9c, 0xe5, 0x58, 0x5a, 0xa8, 0xe4, 0xa0,
	0xfa, 0xde, 0x12, 0xb8, 0xd9, 0x04, 0xf4, 0xe0, 0x4a, 0x9f, 0xc6, 0x74, 0xd5, 0x7b, 0x7f, 0x0a,
	0x9b, 0x29, 0x88, 0x94, 0x3c, 0x54, 0xba, 0x7e, 0xab, 0x9e, 0x62, 0xd9, 0xef, 0xff, 0x10, 0x74,
	0xb9, 0xf8, 0x7b, 0xf3, 0x91, 0x63, 0x8f, 0x0f, 0x49, 0x44, 0x42, 0x1a, 0xad, 0xd9, 0xf7, 0x2f,
	0x73, 0x7d, 0x1f, 0x96, 0xee, 0x7b, 0x21, 0x6b, 0xd3, 0xfd, 0xff, 0x0e, 0xb4, 0x22, 0x2e, 0x69,
	0xea, 0x17, 0x6a, 0x0e, 0xee, 0x56, 0x76, 0x55, 0xc1, 0xcf, 0xe6, 0xe1, 0x03, 0x68, 0xf7, 0xa9,
	0x4a, 0x5f, 0x3d, 0x17, 0x0b, 0xe8, 0xac, 0x82, 0xc9, 0x52, 0x1e, 0x28, 0xf9, 0x38, 0x6a, 0xa6,
	0x12, 0x99, 0x93, 0x27, 0x08, 0xae, 0x0b, 0x17, 0x03, 0x1a, 0x05, 0xc4, 0xf6, 0xe8, 0xe4, 0x84,
	0x23, 0xad, 0x99, 0x14, 0x27, 0x97, 0x94, 0x8f, 0xca, 0x27, 0xa5, 0x98, 0xb7, 0xe9, 0xac, 0x3c,
	0x46, 0xb0, 0x5b, 0x4c, 0x27, 0x3d, 0x1e, 0xa9, 0x71, 0x19, 0x54, 0x37, 0x59, 0x65, 0xc8, 0x06,
	0xe6, 0x04, 0xba, 0xbc, 0xc7, 0xea, 0x0f, 0xaa, 0x47, 0xe6, 0x11, 0x68, 0x45, 0x70, 0xcb, 0x09,
	0x29, 0x1b, 0x9a, 0xe3, 0xa6, 0xea, 0x91, 0xb1, 0xf9, 0x1f, 0xc5, 0x9b, 0xef, 0x13, 0x16, 0xcc,
	0x1c, 0x46, 0x26, 0x3d, 0x87, 0x84, 0x21, 0x5d, 0x33, 0x35, 0xb3, 0x5c, 0x6a, 0xee, 0x97, 0x4e,
	0x4d, 0x31, 0x6d, 0xd3, 0xa1, 0xf9, 0x3e, 0xde, 0x1a, 0x2b, 0x64, 0x4d, 0x9f, 0x30, 0x0a, 0xc1,
	0xea, 0x09, 0xa3, 0x7c, 0x9d, 0x38, 0x9c, 0x04, 0x02, 0xa5, 0x81, 0x50, 0x5d, 0x6f, 0xe5, 0x5c,
	0x97, 0x27, 0x4c, 0x0e, 0xac, 0xe1, 0x13, 0x46, 0x45, 0x17, 0x98, 0xfb, 0x7f, 0x6e, 0xc0, 0xe5,
	0x5e, 0xfc, 0xc3, 0xfb, 0x71, 0x2f, 0xf1, 0xcf, 0x08, 0x2e, 0x29, 0x83, 0x3d, 0x3e, 0xa8, 0xff,
	0xe7, 0x43, 0xeb, 0xd5, 0xc2, 0x88, 0x9d, 0xd0, 0x77, 0x1e, 0xff, 0xfd, 0xe4, 0x87, 0xd6, 0x15,
	0x7c, 0x69, 0xb1, 0x67, 0x92, 0xe5, 0xd7, 0xf8, 0x17, 0x04, 0x17, 0xb3, 0x93, 0x3c, 0x7e, 0xaf,
	0x14, 0x59, 0xc1, 0xbf, 0x09, 0xed, 0x76, 0x0d, 0x04, 0x29, 0xf6, 0x45, 0x21, 0xb6, 0x8d, 0x77,
	0x4c, 0x45, 0xad, 0xf9, 0x0d, 0xef, 0xfa, 0xb7, 0xf8, 0x57, 0x04, 0x9b, 0xf9, 0x79, 0x19, 0x1f,
	0x36, 0x31, 0xd8, 0x6b, 0x77, 0x6a, 0xa2, 0xc8, 0x02, 0x3a, 0xa2, 0x00, 0x8c, 0x37, 0x79, 0x01,
	0xae, 0x73, 0x9a, 0xca, 0xfc, 0x0d, 0xc1, 0x65, 0x75, 0x48, 0x2e, 0x99, 0x91, 0xc2, 0x61, 0xbd,
	0x64, 0x46, 0x8a, 0xa7, 0x74, 0xfd, 0x65, 0xa1, 0xba, 0x8b, 0xdb, 0x79, 0xd5, 0x89, 0xf1, 0x3f,
	0x22, 0x80, 0x74, 0x34, 0xc5, 0xb7, 0xea, 0xcd, 0xcd, 0xda, 0xbb, 0x95, 0xd7, 0x4b, 0xc1, 0x58,
	0x08, 0xbe, 0x88, 0x81, 0x0b, 0x1e, 0xc7, 0xa2, 0x7e, 0x42, 0xf0, 0x42, 0x32, 0x89, 0xe2, 0xb7,
	0xcb, 0xda, 0x92, 0x9d, 0x82, 0xb5, 0x77, 0x2a, 0xae, 0x96, 0xea, 0xba, 0x42, 0xdd, 0x16, 0xbe,
	0x9a, 0xaa, 0x4b, 0x8c, 0xfc, 0x03, 0xc1, 0x56, 0xc1, 0x11, 0x8c, 0xfb, 0x0d, 0xdd, 0x31, 0xb4,
	0xe3, 0xfa, 0x40, 0xb2, 0x0a, 0x4d, 0x54, 0xb1, 0x8d, 0x31, 0xaf, 0x22, 0xbe, 0x63, 0x06, 0x63,
	0x29, 0xf7, 0x77, 0x24, 0xa6, 0x7e, 0x65, 0x69, 0xc9, 0x8d, 0xf8, 0x8c, 0xfb, 0x40, 0xc9, 0x8d,
	0xf8, 0xac, 0x1b, 0x80, 0xfe, 0x8a, 0x50, 0x7f, 0x1d, 0x77, 0x57, 0xd5, 0xcb, 0x5e, 0x1c, 0xbc,
	0xf6, 0xc0, 0x78, 0xfe, 0x23, 0xab, 0xfc, 0xb3, 0xb3, 0xd1, 0x79, 0xf1, 0x80, 0xea, 0xf5, 0xa7,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xdc, 0x6c, 0xa7, 0x56, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogServiceClient interface {
	ListAlgorithm(ctx context.Context, in *ListAlgorithmsRequest, opts ...grpc.CallOption) (*ListAlgorithmsResponse, error)
	GetAlgorithm(ctx context.Context, in *GetAlgorithmRequest, opts ...grpc.CallOption) (*GetAlgorithmResponse, error)
	ListMLFrameworks(ctx context.Context, in *ListMLFrameworksRequest, opts ...grpc.CallOption) (*ListMLFrameworksResponse, error)
	GetMLFramework(ctx context.Context, in *GetMLFrameworkRequest, opts ...grpc.CallOption) (*GetMLFrameworkResponse, error)
	ListClouds(ctx context.Context, in *ListCloudsRequest, opts ...grpc.CallOption) (*ListCloudsResponse, error)
	GetCloud(ctx context.Context, in *GetCloudRequest, opts ...grpc.CallOption) (*GetCloudResponse, error)
	ListWorkloadClasses(ctx context.Context, in *ListWorkloadClassesRequest, opts ...grpc.CallOption) (*ListWorkloadClassesResponse, error)
	GetWorkloadClass(ctx context.Context, in *GetWorkloadClassRequest, opts ...grpc.CallOption) (*GetWorkloadClassResponse, error)
}

type catalogServiceClient struct {
	cc *grpc.ClientConn
}

func NewCatalogServiceClient(cc *grpc.ClientConn) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ListAlgorithm(ctx context.Context, in *ListAlgorithmsRequest, opts ...grpc.CallOption) (*ListAlgorithmsResponse, error) {
	out := new(ListAlgorithmsResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modeld.services.catalog.CatalogService/ListAlgorithm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAlgorithm(ctx context.Context, in *GetAlgorithmRequest, opts ...grpc.CallOption) (*GetAlgorithmResponse, error) {
	out := new(GetAlgorithmResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modeld.services.catalog.CatalogService/GetAlgorithm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListMLFrameworks(ctx context.Context, in *ListMLFrameworksRequest, opts ...grpc.CallOption) (*ListMLFrameworksResponse, error) {
	out := new(ListMLFrameworksResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modeld.services.catalog.CatalogService/ListMLFrameworks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetMLFramework(ctx context.Context, in *GetMLFrameworkRequest, opts ...grpc.CallOption) (*GetMLFrameworkResponse, error) {
	out := new(GetMLFrameworkResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modeld.services.catalog.CatalogService/GetMLFramework", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListClouds(ctx context.Context, in *ListCloudsRequest, opts ...grpc.CallOption) (*ListCloudsResponse, error) {
	out := new(ListCloudsResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modeld.services.catalog.CatalogService/ListClouds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetCloud(ctx context.Context, in *GetCloudRequest, opts ...grpc.CallOption) (*GetCloudResponse, error) {
	out := new(GetCloudResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modeld.services.catalog.CatalogService/GetCloud", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListWorkloadClasses(ctx context.Context, in *ListWorkloadClassesRequest, opts ...grpc.CallOption) (*ListWorkloadClassesResponse, error) {
	out := new(ListWorkloadClassesResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modeld.services.catalog.CatalogService/ListWorkloadClasses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetWorkloadClass(ctx context.Context, in *GetWorkloadClassRequest, opts ...grpc.CallOption) (*GetWorkloadClassResponse, error) {
	out := new(GetWorkloadClassResponse)
	err := c.cc.Invoke(ctx, "/github.com.metaprov.modeld.services.catalog.CatalogService/GetWorkloadClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
type CatalogServiceServer interface {
	ListAlgorithm(context.Context, *ListAlgorithmsRequest) (*ListAlgorithmsResponse, error)
	GetAlgorithm(context.Context, *GetAlgorithmRequest) (*GetAlgorithmResponse, error)
	ListMLFrameworks(context.Context, *ListMLFrameworksRequest) (*ListMLFrameworksResponse, error)
	GetMLFramework(context.Context, *GetMLFrameworkRequest) (*GetMLFrameworkResponse, error)
	ListClouds(context.Context, *ListCloudsRequest) (*ListCloudsResponse, error)
	GetCloud(context.Context, *GetCloudRequest) (*GetCloudResponse, error)
	ListWorkloadClasses(context.Context, *ListWorkloadClassesRequest) (*ListWorkloadClassesResponse, error)
	GetWorkloadClass(context.Context, *GetWorkloadClassRequest) (*GetWorkloadClassResponse, error)
}

// UnimplementedCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCatalogServiceServer struct {
}

func (*UnimplementedCatalogServiceServer) ListAlgorithm(ctx context.Context, req *ListAlgorithmsRequest) (*ListAlgorithmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlgorithm not implemented")
}
func (*UnimplementedCatalogServiceServer) GetAlgorithm(ctx context.Context, req *GetAlgorithmRequest) (*GetAlgorithmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlgorithm not implemented")
}
func (*UnimplementedCatalogServiceServer) ListMLFrameworks(ctx context.Context, req *ListMLFrameworksRequest) (*ListMLFrameworksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMLFrameworks not implemented")
}
func (*UnimplementedCatalogServiceServer) GetMLFramework(ctx context.Context, req *GetMLFrameworkRequest) (*GetMLFrameworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMLFramework not implemented")
}
func (*UnimplementedCatalogServiceServer) ListClouds(ctx context.Context, req *ListCloudsRequest) (*ListCloudsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClouds not implemented")
}
func (*UnimplementedCatalogServiceServer) GetCloud(ctx context.Context, req *GetCloudRequest) (*GetCloudResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCloud not implemented")
}
func (*UnimplementedCatalogServiceServer) ListWorkloadClasses(ctx context.Context, req *ListWorkloadClassesRequest) (*ListWorkloadClassesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkloadClasses not implemented")
}
func (*UnimplementedCatalogServiceServer) GetWorkloadClass(ctx context.Context, req *GetWorkloadClassRequest) (*GetWorkloadClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkloadClass not implemented")
}

func RegisterCatalogServiceServer(s *grpc.Server, srv CatalogServiceServer) {
	s.RegisterService(&_CatalogService_serviceDesc, srv)
}

func _CatalogService_ListAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlgorithmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modeld.services.catalog.CatalogService/ListAlgorithm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListAlgorithm(ctx, req.(*ListAlgorithmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlgorithmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modeld.services.catalog.CatalogService/GetAlgorithm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAlgorithm(ctx, req.(*GetAlgorithmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListMLFrameworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMLFrameworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListMLFrameworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modeld.services.catalog.CatalogService/ListMLFrameworks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListMLFrameworks(ctx, req.(*ListMLFrameworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetMLFramework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMLFrameworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetMLFramework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modeld.services.catalog.CatalogService/GetMLFramework",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetMLFramework(ctx, req.(*GetMLFrameworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListClouds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCloudsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListClouds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modeld.services.catalog.CatalogService/ListClouds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListClouds(ctx, req.(*ListCloudsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetCloud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloudRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetCloud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modeld.services.catalog.CatalogService/GetCloud",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetCloud(ctx, req.(*GetCloudRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListWorkloadClasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadClassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListWorkloadClasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modeld.services.catalog.CatalogService/ListWorkloadClasses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListWorkloadClasses(ctx, req.(*ListWorkloadClassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetWorkloadClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetWorkloadClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.metaprov.modeld.services.catalog.CatalogService/GetWorkloadClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetWorkloadClass(ctx, req.(*GetWorkloadClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.metaprov.modeld.services.catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAlgorithm",
			Handler:    _CatalogService_ListAlgorithm_Handler,
		},
		{
			MethodName: "GetAlgorithm",
			Handler:    _CatalogService_GetAlgorithm_Handler,
		},
		{
			MethodName: "ListMLFrameworks",
			Handler:    _CatalogService_ListMLFrameworks_Handler,
		},
		{
			MethodName: "GetMLFramework",
			Handler:    _CatalogService_GetMLFramework_Handler,
		},
		{
			MethodName: "ListClouds",
			Handler:    _CatalogService_ListClouds_Handler,
		},
		{
			MethodName: "GetCloud",
			Handler:    _CatalogService_GetCloud_Handler,
		},
		{
			MethodName: "ListWorkloadClasses",
			Handler:    _CatalogService_ListWorkloadClasses_Handler,
		},
		{
			MethodName: "GetWorkloadClass",
			Handler:    _CatalogService_GetWorkloadClass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/catalog/catalog.proto",
}
