/**
*
* Copyright (C) 2017 modeld authors
* For license information, see LICENSE.txt
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/metaprov/modeldapi/pkg/apis/data/v1alpha1"
	scheme "github.com/metaprov/modeldapi/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RecipeRunsGetter has a method to return a RecipeRunInterface.
// A group's client should implement this interface.
type RecipeRunsGetter interface {
	RecipeRuns(namespace string) RecipeRunInterface
}

// RecipeRunInterface has methods to work with RecipeRun resources.
type RecipeRunInterface interface {
	Create(ctx context.Context, recipeRun *v1alpha1.RecipeRun, opts v1.CreateOptions) (*v1alpha1.RecipeRun, error)
	Update(ctx context.Context, recipeRun *v1alpha1.RecipeRun, opts v1.UpdateOptions) (*v1alpha1.RecipeRun, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RecipeRun, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RecipeRunList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RecipeRun, err error)
	RecipeRunExpansion
}

// recipeRuns implements RecipeRunInterface
type recipeRuns struct {
	client rest.Interface
	ns     string
}

// newRecipeRuns returns a RecipeRuns
func newRecipeRuns(c *DataV1alpha1Client, namespace string) *recipeRuns {
	return &recipeRuns{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the recipeRun, and returns the corresponding recipeRun object, and an error if there is any.
func (c *recipeRuns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RecipeRun, err error) {
	result = &v1alpha1.RecipeRun{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reciperuns").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RecipeRuns that match those selectors.
func (c *recipeRuns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RecipeRunList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RecipeRunList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reciperuns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested recipeRuns.
func (c *recipeRuns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("reciperuns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a recipeRun and creates it.  Returns the server's representation of the recipeRun, and an error, if there is any.
func (c *recipeRuns) Create(ctx context.Context, recipeRun *v1alpha1.RecipeRun, opts v1.CreateOptions) (result *v1alpha1.RecipeRun, err error) {
	result = &v1alpha1.RecipeRun{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("reciperuns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(recipeRun).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a recipeRun and updates it. Returns the server's representation of the recipeRun, and an error, if there is any.
func (c *recipeRuns) Update(ctx context.Context, recipeRun *v1alpha1.RecipeRun, opts v1.UpdateOptions) (result *v1alpha1.RecipeRun, err error) {
	result = &v1alpha1.RecipeRun{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("reciperuns").
		Name(recipeRun.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(recipeRun).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the recipeRun and deletes it. Returns an error if one occurs.
func (c *recipeRuns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reciperuns").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *recipeRuns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reciperuns").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched recipeRun.
func (c *recipeRuns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RecipeRun, err error) {
	result = &v1alpha1.RecipeRun{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("reciperuns").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
