# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from github.com.metaprov.modelaapi.services.predictor.v1 import predictor_pb2 as github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in github.com/metaprov/modelaapi/services/predictor/v1/predictor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PredictorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPredictors = channel.unary_unary(
                '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/ListPredictors',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.ListPredictorsRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.ListPredictorsResponse.FromString,
                _registered_method=True)
        self.CreatePredictor = channel.unary_unary(
                '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/CreatePredictor',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.CreatePredictorRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.CreatePredictorResponse.FromString,
                _registered_method=True)
        self.GetPredictor = channel.unary_unary(
                '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/GetPredictor',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.GetPredictorRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.GetPredictorResponse.FromString,
                _registered_method=True)
        self.UpdatePredictor = channel.unary_unary(
                '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/UpdatePredictor',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.UpdatePredictorRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.UpdatePredictorResponse.FromString,
                _registered_method=True)
        self.RollBack = channel.unary_unary(
                '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/RollBack',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.RollbackRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.DeletePredictor = channel.unary_unary(
                '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/DeletePredictor',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.DeletePredictorRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.DeletePredictorResponse.FromString,
                _registered_method=True)
        self.PredictOne = channel.unary_unary(
                '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/PredictOne',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.PredictOneRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.PredictOneResponse.FromString,
                _registered_method=True)


class PredictorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListPredictors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePredictor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredictor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePredictor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollBack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePredictor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPredictors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPredictors,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.ListPredictorsRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.ListPredictorsResponse.SerializeToString,
            ),
            'CreatePredictor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePredictor,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.CreatePredictorRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.CreatePredictorResponse.SerializeToString,
            ),
            'GetPredictor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictor,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.GetPredictorRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.GetPredictorResponse.SerializeToString,
            ),
            'UpdatePredictor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePredictor,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.UpdatePredictorRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.UpdatePredictorResponse.SerializeToString,
            ),
            'RollBack': grpc.unary_unary_rpc_method_handler(
                    servicer.RollBack,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.RollbackRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.RollbackResponse.SerializeToString,
            ),
            'DeletePredictor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePredictor,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.DeletePredictorRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.DeletePredictorResponse.SerializeToString,
            ),
            'PredictOne': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictOne,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.PredictOneRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.PredictOneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'github.com.metaprov.modelaapi.services.predictor.v1.PredictorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('github.com.metaprov.modelaapi.services.predictor.v1.PredictorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPredictors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/ListPredictors',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.ListPredictorsRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.ListPredictorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePredictor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/CreatePredictor',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.CreatePredictorRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.CreatePredictorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredictor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/GetPredictor',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.GetPredictorRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.GetPredictorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePredictor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/UpdatePredictor',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.UpdatePredictorRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.UpdatePredictorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollBack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/RollBack',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.RollbackRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePredictor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/DeletePredictor',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.DeletePredictorRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.DeletePredictorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/github.com.metaprov.modelaapi.services.predictor.v1.PredictorService/PredictOne',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.PredictOneRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_predictor_dot_v1_dot_predictor__pb2.PredictOneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
