# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from github.com.metaprov.modelaapi.services.genai.v1 import genai_pb2 as github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2


class GenAIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Refresh = channel.unary_unary(
                '/GenAIService/Refresh',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.RefreshRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.RefreshResponse.FromString,
                )
        self.Teardown = channel.unary_unary(
                '/GenAIService/Teardown',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.TeardownRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.TeardownResponse.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/GenAIService/Shutdown',
                request_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.ShutdownResponse.FromString,
                )


class GenAIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teardown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.RefreshRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.RefreshResponse.SerializeToString,
            ),
            'Teardown': grpc.unary_unary_rpc_method_handler(
                    servicer.Teardown,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.TeardownRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.TeardownResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.ShutdownRequest.FromString,
                    response_serializer=github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GenAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenAIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GenAIService/Refresh',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.RefreshRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.RefreshResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Teardown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GenAIService/Teardown',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.TeardownRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.TeardownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GenAIService/Shutdown',
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.ShutdownRequest.SerializeToString,
            github_dot_com_dot_metaprov_dot_modelaapi_dot_services_dot_genai_dot_v1_dot_genai__pb2.ShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
